# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  script:
    - mkdir .public
    - cp -r doc/* .public
    # override edoc generated README
    - cp README.md doc/README.md
    - mv .public public
  artifacts:
    paths:
      - public
  # only:
  #   - master
