# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
    # override edoc generated README
    - if [ ! -d public ]; then mkdir public; fi
    - mkdir .public
    - cp -r doc/* .public
    - cp README.md .public/README.md
    - mv .public public
  artifacts:
    paths:
      - public
  # only:
  #   - master
